# Generated by Django 5.0.4 on 2024-04-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='max_notifications',
            new_name='max_changes',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='prestation_name',
            new_name='provider',
        ),
        migrations.AddField(
            model_name='contract',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
