# Generated by Django 5.0.4 on 2024-04-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='provider',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='max_changes',
        ),
    ]
